### ISSUE TITLE
Error: 'Error {     code=404;     message="Not Found: Currently unknown

### ISSUE THREAD

**Issue by AUFS19** [ERDDAP/erddap#130]
Hi, 

when trying to extract data info on datasets in R, I keep getting an error message.  This happened with a variety of datasets. 

Error: 'Error {
    code=404;
    message="Not Found: Currently unknown datasetID=nesdisNPPN20S3ASCIDINEOFDaily";
}
' does not exist in current working directory ('').

I have seen this has been a problem before, but I tried with all the suggestions, and unfortunately didn't manage to fix this. I have even tried to download data from the website, but this is the error message I'm getting. 

Error {
    code=404;
    message="Not Found: Your query produced no matching results.

I was wondering if you could help me. 

My code: 

chlaInfo <- info('nesdisNPPN20S3ASCIDINEOFDaily')

**Comment by ChrisJohnNOAA** [comment]
It sounds like a problem with a dataset. What server are you connecting to? Have you tried reaching out to the admin of that server?

**Comment by ChrisJohnNOAA** [comment]
I'm closing this since I believe it's an issue with the specific server (maybe they removed that dataset) or dataset (maybe it's temporarily unavailable). Without further evidence of a systemic problem there's nothing to do on the ERDDAP project side of things.
