### ISSUE TITLE
Nanoseconds in relative time units causes error

### ISSUE THREAD

**Issue by benjwadams** [ERDDAP/erddap#216]
**Describe the bug**
Conversion from relative time units containing nanoseconds causes an exception when attempting to convert in ERDDAP's internal routines.

**To Reproduce**
1) Add a dataset with time `units` attribute set to something with `nanoseconds`, e.g. `nanoseconds since 1970-01-01T00:00:00+00:00`.
2) Add dataset to `datasets.xml` to be inventoried by ERDDAP.
3) Dataset does not appear and a Java calendar exception is raised in the ERDDAP log file.

Excerpt from email correspondence where this issue was encountered:

<blockquote>
Apparently ERDDAP doesn’t like something with a time related quantity:

```
While trying to load datasetID=dfo-hal1002-20020724T1839 (after 23 ms)
java.lang.RuntimeException: datasets.xml error on or before line #731958: ERROR in Calendar2.factorToGetSeconds: units="nanoseconds" is invalid.
at gov.noaa.pfel.erddap.dataset.EDD.fromXml(EDD.java:486)
at gov.noaa.pfel.erddap.LoadDatasets.run(LoadDatasets.java:364)
Caused by: java.lang.RuntimeException: ERROR in Calendar2.factorToGetSeconds: units="nanoseconds" is invalid.
at com.cohort.util.Test.error(Test.java:43)
at com.cohort.util.Calendar2.factorToGetSeconds(Calendar2.java:2725)
at com.cohort.util.Calendar2.getTimeBaseAndFactor(Calendar2.java:2550)
at com.cohort.util.Calendar2.getTimeBaseAndFactor(Calendar2.java:2518)
at gov.noaa.pfel.erddap.variable.EDVTimeStamp.<init>(EDVTimeStamp.java:186)
at gov.noaa.pfel.erddap.variable.EDVTime.<init>(EDVTime.java:27)
at gov.noaa.pfel.erddap.dataset.EDDTableFromFiles.<init>(EDDTableFromFiles.java:1778)
at gov.noaa.pfel.erddap.dataset.EDDTableFromNcFiles.<init>(EDDTableFromNcFiles.java:131)
at gov.noaa.pfel.erddap.dataset.EDDTableFromFiles.fromXml(EDDTableFromFiles.java:501)
at gov.noaa.pfel.erddap.dataset.EDD.fromXml(EDD.java:472)
```

After looking at ncdump output, it appears that time variable units are expressed as “nanoseconds since 1970-01-01 00:00:00” or something very similar.  I believe this is valid UDUnits and should be fine with CF as well, but ERDDAP doesn’t seem to like converting that unit with the module they have there.  If the previous sentence is correct, I’d argue that this is a bug/deficiency of ERDDAP.  If you’d like to get the files read in the meantime, I’d recommend converting over to at least seconds.
</blockquote>

I have yet to encounter or test any datasets with even smaller time intervals such as picoseconds, but I imagine this issue may also exist with them.

**Expected behavior**
Relative time units expressed in nanoseconds ("nanoseconds since 1970-01-01T00:00:00+00:00") converts properly since it should be a valid UDUnits relative time.

**Server**
- ERDDAP 2.23 Axiom Docker image

**Desktop (please complete the following information):**
- Linux x86-64

**Additional context**

**Comment by ChrisJohnNOAA** [comment]
Milliseconds is the most fine grained time measurement currently supported in ERDDAP. https://github.com/ERDDAP/erddap/blob/main/WEB-INF/classes/com/cohort/util/Calendar2.java#L5741-L5770

**Comment by benjwadams** [comment]
This is surprising behavior because UDUNITS2 allows for all the way down to yocto (10^-24) prefixes on units: https://github.com/Unidata/UDUNITS-2/blob/c83da987387db1174cd2266b73dd5dd556f4476b/lib/udunits2-prefixes.xml#L74

 While it's unlikely that the sort of data ERDDAP Is usually serving would have this fine of a time resolution, it is nonetheless valid in UDUNITS2 to express something like `yoctoseconds since 2024-01-01+00:00`.

An acceptable enough fix would be to parse that unit and switch/case a power of ten multiplier to convert the relative time prefix back to milli_(time interval)_ in the event that the Java calendar library threw an an exception.

**Comment by ChrisJohnNOAA** [comment]
The ERDDAP documentation for handling time units is here: https://erddap.github.io/setupDatasetsXml.html#timeUnits

It doesn't strictly follow UDUNITS2. ERDDAP doesn't use UDUNITS2 for time conversions. Adding additional time units (even just for time conversion) is possible but more work than a power of ten conversion in one spot. Additionally in several places the java.util.Date library is still used which only has millisecond precision. To properly support nanoseconds we'd need to update that code to a different library or verify it doesn't need the additional precision. Past nanosecond accuracy and standard java time libraries don't support that. Power of ten conversion only support might be possible, but I wonder how beneficial that is, especially if users don't realize they are loosing the precision they think they have.

**Comment by srstsavage** [comment]
Definitely the most efficient workaround here would be to convert the source data time variable to use millisecond or coarser precision. But, if that's not convenient/possible/etc, you could try doing that conversion in datasets.xml using a JEXL expression.

Example:

```
    <dataVariable>
        <!-- convert nanosecond time precision to seconds -->
        <sourceName>=row.columnLong("time")/1e+9</sourceName>
        <destinationName>time</destinationName>
        <dataType>long</dataType>
        <!-- sourceAttributes>
        </sourceAttributes -->
        <addAttributes>
            <att name="ioos_category">Time</att>
            <att name="long_name">Time</att>
            <att name="standard_name">time</att>
            <att name="units">seconds since 1970-01-01T00:00:00Z</att>
        </addAttributes>
    </dataVariable>
```

Worked for me when experimenting with the new parquet support, YMMV.

**Comment by benjwadams** [comment]
Wasn't aware of this bit of ERDDAP, but it looks like it's been around for quite some time.  Thanks for the info.
