### ISSUE TITLE
MD5 for v2.25.1 listed in DEPLOY_INSTALL.md and UPDATE_INSTALL.md does not match downloaded file

### ISSUE THREAD

**Issue by alexdioso** [ERDDAP/erddap#232]
The MD5 I'm getting for [v2.25.1](https://github.com/ERDDAP/erddap/releases/download/v2.25.1/erddap.war) is 652afc9d1421f00b5f789da2c4732d4c. I've checked multiple times on different servers. The MD5 listed in the docs is 0F0C14FD22DF80D0E867A4B96ED7F3FF. Can someone confirm which one is correct?

Thanks.

**Comment by ChrisJohnNOAA** [comment]
652AFC9D1421F00B5F789DA2C4732D4C is the proper hash for the released version. The other hash was of a build that had a minor documentation change before release. The documentation will be updated shortly with the proper hash.
