### ISSUE TITLE
Time issue erddap cache vs on disk. 

### ISSUE THREAD

**Issue by thogar-computer** [ERDDAP/erddap#62]
Hiya all, 
not sure if this is my misuse of a feature or a bug? 

### Issue
 
The address https://linkedsystems.uk/erddap/tabledap/ea_sea_level_e72224_e229_390e_c509.htmlTable?&time=max(time) resulted in a error of; 

``` 
{
    code=404;
    message="Not Found: Your query produced no matching results. (No data matches time=\"1.6341291E9\" because the String variable's source min=\"2020-10-30T13:15:00Z\", max=\"2021-10-13T12:30:00Z\", and hasNaN=false.)";
}
```
https://linkedsystems.uk/erddap/tabledap/ea_sea_level_e72224_e229_390e_c509.htmlTable?&time=max(time)+0minutes gave the same error. 

interestingly the address https://linkedsystems.uk/erddap/tabledap/ea_sea_level_e72224_e229_390e_c509.htmlTable?&time=max(time)+1minutes shows an error with formatted time, and states that the requested time is outside of the range for this datatset.

```
{
    code=404;
    message="Not Found: Your query produced no matching results. (time=2021-10-13T12:46:00Z is outside of the variable's actual_range: 2020-10-30T13:15:00Z to 2021-10-13T12:45:00Z)";
}
```

The following address https://linkedsystems.uk/erddap/tabledap/ea_sea_level_e72224_e229_390e_c509.htmlTable?&time%3Cmax(time) shows all data.

and if i make time a variable like so https://linkedsystems.uk/erddap/tabledap/ea_sea_level_e72224_e229_390e_c509.htmlTable?time&time=max(time) the page worked.  

## Issue found
After some more digging it turns out that the erddap metadata was very slightly out of date with what was on disk. i.e the max time value was in fact 2021-10-13T12:45:00Z  and as can be seen from the error reported the erddap max range was 2021-10-13T12:30:00Z. Resulting in the URL erroring out. 
  

### questions

- Why isn't the time formatted in the first error message?
- Should a request containing a + or > on a max variable be a 400 error?
- I am not entirely sure why naming the variable (in this case time) changes the behaviour between requests?

**Comment by joe-smithe-glos** [comment]
@thogar-computer did you figure out what was causing the issue here? Trying to see if an issue I'm having may be related (https://groups.google.com/g/erddap/c/0i7tSy9LOLE): There's a disconnect between the actual_range ERDDAP produces for the front-end and the time range of the source data, even though DasDds picks up the correct range. 

Still looking into it here so I may learn more later
