### ISSUE TITLE
ERDDAP not sending emails when emailUserName is not an email address

### ISSUE THREAD

**Issue by turnbullerin** [ERDDAP/erddap#99]
Hi!

I've been having a weird issue where I'm not getting any emails from ERDDAP despite the connection properties all working when I try to send mail using Python from the same server.

I think I tracked down the error though. ERDDAP detects if email is active with this:

emailIsActive = //ie if actual emails will be sent
            String2.isSomething(emailSmtpHost) &&
            emailSmtpPort > 0 &&
            String2.isEmailAddress(emailUserName) &&
            String2.isSomething(emailPassword) &&
            String2.isEmailAddress(emailFromAddress);

However, because I am using a mail API client (think Twilio, because my security department insists its the only way I'm allowed to send email), my emailUserName is NOT an email address, it is an alphanumeric string (e.g. USER12345). Since this check fails, ERDDAP thinks my email settings aren't valid and won't send email.

Can we get a patch to have emailIsActive only check if emailUserName isSomething() instead?

Erin

**Comment by srstsavage** [comment]
Looks like @ChrisJohnNOAA fixed this two weeks ago in https://github.com/ERDDAP/erddap/commit/48a4759f331e12c990bb1e0251671e42922b6995. Should be in the 2.25 release.

**Comment by ChrisJohnNOAA** [comment]
Yeah, #174. Marking this as closed now. It will be in the 2.25 release as @srstsavage mentioned.

**Comment by srstsavage** [comment]
Ah I see the discussion in https://github.com/ERDDAP/erddap/issues/173 now. Thanks @turnbullerin for submitting a fix for that!
